### PR TITLE
Revert 156 aksoybranch

### PR DESCRIPTION
**Pull request by e7hdk**

### CODE REVIEW

**Comment by GozdeUnver** [comment]
There is no valid code in authentication app

**Comment by GozdeUnver** [comment]
Authentication is like a separate django projects, it has settings.py etc. It can't be like that. It must be an app of the group5_api project. You should create an app using this command "python manage.py startapp authentication"

**Comment by GozdeUnver** [comment]
You should provide API documentation and unit tests

**Comment by berkaybor** [comment]
We should delete this branch, it is not needed.

**Pull request closed without merging**
