### PR TITLE
Login, Register, Forgot Password Validaitons and Tests

### PR DESCRIPTION
**Pull request by zudiay**
in functions.js, implemented string input validation functions(validateAlphaNumeric, validateContainsNumberAndLetter, validateUsername, validateEmail, validatePassword) to use on registration
in ForgotPasswordScreen.jsx, RegisterScreen.jsx, LoginScreen.jsx, added necessary data test ids
in LoginScreen.jsx, removed user prop from LoginScreen. connected Forgot Password button to navigate to the forgot password page
in RegisterScreen.jsx, added input validations to onRegister using getValues. Implemented necessary error messages. Added Previous Step button to navigate to form step 1. Solved the bug with Next button on step 1 submitting the form using preventDefault().
in package.json, added jest to dependencies and devDependencies
removed default test App.test.js
in forgotPasswordScreen.test.js, loginScreen.test.js, registerScreen.test.js checked the existence of necessary fields and buttons
in functions.test.js, tested helper functions with different inputs

### CODE REVIEW

**Comment by zudiay** [comment]
> * I reviewed the validations you implemented and it is working as expected.
> * I reviewed the flows of the pages and it is working as expected
> * I also run the test you wrote and they are successful
> 
> However, I want to mention one topic. When a user wants to register, there is not any button in login screen to navigate the register screen. Can you also implement a button for this task?

Hi Furkan! Thank you for the review, you made an important point. I will implement a navigation button to register screen on login screen ASAP.

**Comment by zudiay** [comment]
Hi @atasoyfurkan . I implemented the feature you asked for. Can you check?

**Comment by atasoyfurkan** [comment]
I checked it. It is working perfectly! Thank you for your contribution.

**Comment by atasoyfurkan** [comment]
I resolved the conflicts.

**Comment by zudiay** [comment]
Thank you!

**Pull request merged**
