### PR TITLE
Berkaybranch

### PR DESCRIPTION
**Pull request by berkaybor**
I created my Air Quality API

### CODE REVIEW

**Comment by atasoyfurkan** [comment]
I read your code, cloned the repository to my local, run it, and test it via Postman and also with unit tests you wrote. I like the functionality of API, it is good to know how pollute an environment with an API. I wrote things I checked, and I have some suggestions for you. 

Things I checked:
* I read the code carefully, and check what functionality it has
    * As I see all edge cases are handled.
    * Coding is organized
* I test the functionality of API with postman. It is working without any problem.
* I read unit test code it is well-written. I reported my observation below.
* I compared API with job description to see is there any missing points. I reported it below.
* I check project to see is there any possible merging issue which makes other team members’ work harder. I reported it below.


Suggestions:
* In unit test, I think it would be better for you to check if the response body is in desired form, contains necessary keys.
* You should add an user interface for your API to make interaction with API easy.
* You should add a home app and connect your application to it with name like “airPollution” before merging. (You can get home app from master branch)
    * Also, you should change project name as “group5_api” to make merging easy

**Review by atasoyfurkan — CHANGES_REQUESTED** [review]
I read your code, cloned the repository to my local, run it, and test it via Postman and also with unit tests you wrote. I like the functionality of API, it is good to know how pollute an environment with an API. I wrote things I checked, and I have some suggestions for you. 

Things I checked:
* I read the code carefully, and check what functionality it has
    * As I see all edge cases are handled.
    * Coding is organized
* I test the functionality of API with postman. It is working without any problem.
* I read unit test code it is well-written. I reported my observation below.
* I compared API with job description to see is there any missing points. I reported it below.
* I check project to see is there any possible merging issue which makes other team members’ work harder. I reported it below.


Suggestions:
* In unit test, I think it would be better for you to check if the response body is in desired form, contains necessary keys.
* You should add an user interface for your API to make interaction with API easy.
* You should add a home app and connect your application to it with name like “airPollution” before merging. (You can get home app from master branch)
    * Also, you should change project name as “group5_api” to make merging easy

**Comment by berkaybor** [comment]
I have made the changes as you specified, can you review them?

**Comment by atasoyfurkan** [comment]
I reviewed changes. It is okay as I specified. You can merge branch.

**Review by atasoyfurkan — APPROVED** [review]
I reviewed changes. It is okay. You can merge branch.

**Pull request merged**
