### PR TITLE
Home Screen: Implement Previous event functionalities and UI

### PR DESCRIPTION
**Pull request by atasoyfurkan**
- Implement the UI
    - Cards will be shown as events which will show upcoming events of followed users
       - Show capacity
       - Show time
       - Show title
       - Show category
       - Show photo
    - A title will be shown as describing the functionality
- Implement functionalities
   - When the card is clicked, the user will be navigated to the event detail page
   - A get request will send to the backend to fetch upcoming events of followed users.

### CODE REVIEW

**Comment by zudiay** [comment]
Hi Furkan! I tried to run your code on my local and got the following error:
``` 
./src/screens/HomeScreen.js
Module not found: Can't resolve '../components/Common/Badge' in '/Users/didemaytac/WebstormProjects/2021SpringGroup5/project/frontend/app/src/screens'
```
I think this may be because you implemented the badge component at the same time but pushed it to a different branch. Can you check?

**Comment by atasoyfurkan** [comment]
Yes, the problem was what you said. I resolved it.

**Comment by atasoyfurkan** [comment]
I am merging the pull request because I solved the issue Didem stated and everything works fine.

**Comment by zudiay** [comment]
Thank you Furkan! It looks really good and I like that it redirects to the related event page. 👍

**Pull request merged**
