### PR TITLE
Implement Send badge functionality and Unit Tests

### PR DESCRIPTION
**Pull request by atasoyfurkan**
- Implement the functionalities of Badge
    - Connect with backend
    - Implement Badge UI
        - A menu will be used for showing badges
        - A button will be used to open the menu 
    - Implement Badge functionalities
       - When the menu is clicked, all available badges will be shown
       - All available badges information will be fetched at the beginning of rendering from the backend
       - When a badge name is clicked, the badge will be sent to the chosen user. 
       - Check that whether event is finished or not, then show the badge button if the event is finished
 - Unit Tests

### CODE REVIEW

**Comment by zudiay** [comment]
Hi Furkan! I pulled your code and reviewed it. I saw that you added the Badge component to ParticipantListingPage but not to ParticipantListingRow. Can you also add it, because ParticipantListingRow is the component that the event creator sees. And if it is not added, the creator cannot send badges. You can see it in detail in ParticipantsAdmin component.
sendBadge.test.js test passes 👍 I tried the send badge functionality on an event another user has created and it works perfectly. I went to the profile and verified it is available there. Thank you.

**Comment by zudiay** [comment]
It would be nice to show the send badge button for the accepted users only. I render that row at
 ``` 
<ParticipantListingRow
        participants={accepted_players}
        title="Accepted Participants"
        actionable={false}
        event={event}
      />
```
In ParticipantListingRow, you can add the badge component if the title is "Accepted Participants" so that it is only shown in that row.

**Comment by atasoyfurkan** [comment]
It is correct Didem. I added this feature as well. You can look at it. Thank you for your detailed feedback.

**Comment by zudiay** [comment]
I checked it and it works well. Thank you for your quick response. I am merging the branch to master.

**Pull request merged**
